name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build  # Thay thế bằng lệnh build phù hợp nếu bạn không dùng Gradle

    - name: Run Tests
      run: ./gradlew test  # Thay thế bằng lệnh test nếu bạn không dùng Gradle
